first_project/first_app/urls.py
from django.contrib import admin
from django.urls import path
from first_app import views

app_name = 'first_app'

urlpatterns = [
    path('register/', views.registration, name = 'register'),
    path('login/', views.user_login, name = 'user_login'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from first_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('first_app/', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/$', views.user_logout, name = 'user_logout'),
    path('special/', views.special, name = 'special'),
]

first_project/first_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, models.SET_NULL, null = True)

    #PORTFOLIO
    portfolio_site = models.URLField(blank=True)
    profile_pic= models.ImageField(upload_to = 'profile_pics', blank=True)
    def __str__(self):
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name

class Webpage(models.Model):
    topic = models.ForeignKey(Topic,models.SET_NULL, null = True)
    name = models.CharField(max_length = 264, unique = True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name

class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage,models.SET_NULL, null = True)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

first_project/first_app/forms.py
from django import forms
from django.core import validators
from first_app.models import UserProfileInfo,Topic, Webpage, AccessRecord
from django.contrib.auth.models import User

# def check_for_z(value):
#     if value[0].lower =! "z":
#         raise forms.ValidationError("Names need to start with Z")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta():
        model = User
        fields = ['username','email','password']

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ['portfolio_site','profile_pic']

class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField(label= "Enter your email again")
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False, widget=forms.HiddenInput, validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("Email is not matching")
    
# class myNewForm(forms.ModelForm):
#     class Meta:
#         model = Webpage
#         fields = ["field1", "field2"]

first_project/first_app/views.py
from django.shortcuts import render, redirect
from first_app.models import Topic, Webpage, AccessRecord
from first_app.forms import FormName, UserProfileForm, UserForm

#for login handler
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect


def user_login(request): #make sure this is not named as login/logout, as it will overwrite fn above
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account is not active")
        else:
            print("login failed")
            print(f'{username} and {password} failed')
            return HttpResponse("Invalid login")
    else:
        return render(request, 'first_app/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index')) 

@login_required
def special(request):
    return HttpResponse("you are logged in, nice")


# Create your views here.

def index(request):
    webpage_list = AccessRecord.objects.order_by('date')
    date_dict = {'access_rec' : webpage_list}
    return render(request, r'first_app\index.html', context = date_dict)
# each view needs its function - this view is called index
# each view takes at least one argument
# usually called request by convention
# each view MUST return in HTTPresponse object



def registration(request):
    registered = False
    user_form = UserForm()
    profile_form = UserProfileForm()

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    
    return render(request, 'first_app/form_page.html', 
    {'user_form' : user_form , 'profile_form': profile_form, 'registered' : registered })


def form_name_view(request):
    form = FormName()

    if request.method == 'POST':
        form = FormName(request.POST)

        if form.is_valid():
            # do something code will work
            print("VALIDATION SUCCESS")
            print("Name :" + form.cleaned_data['name'])
            print("EMAIL :" + form.cleaned_data['email'])
            print("TEXT :" + form.cleaned_data['text'])

    return render(request, r'first_app\form_page.html', {'form' : form})

first_project/templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>TITLE SMAE SAME HERE</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">


    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class='container'>
                <ul class='navbar-nav'>
                    <li class='nav-item'><a href="{% url 'index' %}" class = "nav-link">Home Page</a></li>
                    <li class='nav-item'><a href="{% url 'admin:index' %}" class = "nav-link">Admin</a></li>
                    <li class='nav-item'><a href="{% url 'first_app:register' %}" class = "nav-link">Register Here</a></li>
                    <li class='nav-item'><a href="{% url 'special' %}" class = "nav-link">Special Page</a></li>

                    {% if user.is_authenticated %}
                    <li class='nav-item'><a href="{% url 'user_logout' %}" class = "nav-link">Logout</a></li>
                    
                    {% else %}
                    <li class='nav-item'><a href="{% url 'first_app:user_login' %}" class = "nav-link">Login</a></li>
                    {% endif %}
                </ul>

            </div>
        </nav>
        
        <div class='container'> 
            {% block body_block %}
            <!-- anything inside will be unique to other html -->
            {% endblock %}
        </div>


    </body>
</html>

first_project/templates/first_app/form_page.html
<!DOCTYPE html>
{%extends 'first_app/base.html' %}
{%block body_block %}
        {% if registered %}
        <h1>Thank you for registering!</h1>
        {%else%}

        <h1>Fill Up the Form here</h1>
        <div class="container">
            <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit"class="btn btn-primary" value="Submit">
          </form>
        </div>
        {% endif %}
{% endblock %}

first_project/templates/first_app/index.html
<!DOCTYPE html>
{%extends 'first_app/base.html' %}
{%block body_block %}
<h1>Hi, welcome to django level two</h1>
        <h2>here are your access record:</h2>

        <div class = 'django2'>
            {% if access_rec %}
            <table>
                <thead>
                    <th>Site Name</th>
                    <th>Date Accessed</th>
                </thead>
            

            {%for acc in access_rec %}
            <tr>
                <td>{{acc.name}}</td>
                <td>{{acc.date}}</td>
            </tr>
            {%endfor%}

            {%else%}
            <p>No Access Records Found!</p>
            {%endif%}

            </table>
        </div>


{% endblock %}

        
    

first_project/templates/first_app/login.html
{% extends 'first_app/base.html' %}

{% block body_block%}

<div class = 'container'>
    <div class = 'jumbotron'>
        <h1>Please login</h1>
        <form action="{% url 'first_app:user_login' %}" method='POST'>
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username: </label>
                <input type="text" class="form-control" name = 'username' id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter User Name">
                <small id="emailHelp" class="form-text text-muted">We'll never share your user name with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" name = 'password' class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <div class="form-group form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
            

        </form>


    </div>


</div>


{% endblock %}